server:
  port: 8888
  
logging:
  level:
    org.springframework.cloud: 'INFO'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dounine/qssc-config-repo
          basedir: target/config